services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/ssl/certs/cert.pem
      - ./key.pem:/etc/ssl/certs/key.pem
    depends_on:
      - template
      - auth
      - conversation
      - conversation-worker

  template:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE=template
    env_file:
      - .env.dev
    environment:
      - DB_SCHEMA=template
    deploy:
      replicas: 3
    volumes:
      - ./services/template:/app
      - ./lib:/app/lib

  auth:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE=auth
    env_file:
      - .env.dev
    environment:
      - DB_SCHEMA=auth
    deploy:
      replicas: 3
    volumes:
      - ./services/auth:/app
      - ./lib:/app/lib

  conversation:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE=conversation
    env_file:
      - .env.dev
    environment:
      - DB_SCHEMA=conversation
    deploy:
      replicas: 3
    volumes:
      - ./services/conversation:/app
      - ./lib:/app/lib

  conversation-worker:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
      args:
        - SERVICE=conversation
    command: ["python", "worker.py"]
    env_file:
      - .env.dev
    environment:
      - DB_SCHEMA=conversation
    deploy:
      replicas: 3
    volumes:
      - ./services/conversation:/app
      - ./lib:/app/lib

networks:
  shared-net:
    name: net
